### ISSUE TITLE
test failed on linux

### ISSUE THREAD

**Issue by remilauzier** [glium/glium#1995] opened 2022-02-15 08:05 UTC
Not sure why the test don't pass.
https://download.copr.fedorainfracloud.org/results/remilauzier/rust-simp/fedora-rawhide-x86_64/03498785-rust-glium/builder-live.log.gz

failures:

---- basic stdout ----
thread 'basic' panicked at 'Initializing the event loop outside of the main thread is a significant cross-platform compatibility hazard. If you really, absolutely need to create an EventLoop on a different thread, please use the `EventLoopExtUnix::new_any_thread` function.', /usr/share/cargo/registry/winit-0.24.0/src/platform_impl/linux/mod.rs:741:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by est31** [comment] 2022-02-15 11:54
Dupe of #1931 and #1780.

**Closed by est31** 2022-02-15 11:54 UTC
