### ISSUE TITLE
Encountered "Debug message with high or medium severity: `GL_INVALID_OPERATION in glGetProgramStageiv`." while trying to use compute shader

### ISSUE THREAD

**Issue by moritzvoelker** [glium/glium#2024] opened 2022-10-08 14:05 UTC
Hello together,
while using glium to play around with rust and OpenGL, more specifically compute shaders, I encountered a weird issue, where the program wouldn't crash, but print out this error message:
```
Debug message with high or medium severity: `GL_INVALID_OPERATION in glGetProgramStageiv`.
Please report this error: https://github.com/glium/glium/issues
Backtrace:
   1 - 0x558195a10341
         _ZN9backtrace9backtrace9libunwind5trace17h8664b0b54fbf4af0E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93
         _ZN9backtrace9backtrace20trace_unsynchronized17hb83f0ff590be0565E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66
   2 - 0x558195a103dc
         _ZN9backtrace9backtrace5trace17hb18e31c5b99d66b2E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53
   3 - 0x558195a13be5
         _ZN5glium7context22default_debug_callback17h61b8e0c89232fee4E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/context/mod.rs:849
   4 - 0x55819586d6fb
         _ZN4core3ops8function5FnMut8call_mut17h2b2454ad74e1bb2bE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:164
   5 - 0x558195a0688c
         _ZN89_$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnMut$LT$Args$GT$$GT$8call_mut17hd92571b0e664990aE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1942
   6 - 0x558195a14dac
         _ZN5glium7context19init_debug_callback16callback_wrapper17h66aad334ae785d9dE at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/context/mod.rs:936
   7 - 0x7f316236b5a1
   8 - 0x5581959c77c9
         _ZN5glium2gl2Gl17GetProgramStageiv17hc2eb3da779289f7bE at /home/moritz/programming/rust/ants/target/debug/build/glium-fae8c5bb5065afdf/out/gl_bindings.rs:6969
   9 - 0x5581959bf5af
         _ZN5glium7program10reflection23reflect_subroutine_data17h27960e08dcd232dcE at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/program/reflection.rs:1240
  10 - 0x55819590e739
         _ZN5glium7program3raw10RawProgram12from_shaders17hb4c8aa288ec48c5fE at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/program/raw.rs:173
  11 - 0x5581958d948c
         _ZN5glium7program7compute13ComputeShader11from_source17h0da2e9316004f507E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/program/compute.rs:52
  12 - 0x558195878f30
         _ZN4ants4main17h872b8896e5a8cdfbE at /home/moritz/programming/rust/ants/src/main.rs:45
  13 - 0x55819586e9ab
         _ZN4core3ops8function6FnOnce9call_once17h21f73aa820a1d6a8E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248
  14 - 0x5581958c592e
         _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h90d6d3722f992330E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:122
  15 - 0x5581958949d1
         _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17hc2271bb8123a1baeE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:145
  16 - 0x55819600ef0e
         _ZN4core3ops8function5impls72_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$9call_once17hcdfee62722e5e4b8E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280
         _ZN3std9panicking3try7do_call17h84ca51609826746fE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492
         _ZN3std9panicking3try17hd58075e533b8e0cbE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456
         _ZN3std5panic12catch_unwind17h1ebac24d83cb6ce2E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137
         _ZN3std2rt19lang_start_internal28_$u7b$$u7b$closure$u7d$$u7d$17h0145388a1edd1640E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128
         _ZN3std9panicking3try7do_call17h7630182e534a0a32E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492
         _ZN3std9panicking3try17h05b6544f0c6331dcE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456
         _ZN3std5panic12catch_unwind17h77b2ba8fd3309f34E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137
         _ZN3std2rt19lang_start_internal17h6612c8a7a6861b8bE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128
  17 - 0x5581958949a0
         _ZN3std2rt10lang_start17hc1cb435e3823b32bE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:144
  18 - 0x55819587996c
         main at <unknown>:??
  19 - 0x7f3164835290
  20 - 0x7f316483534a
         __libc_start_main at <unknown>:??
  21 - 0x558195853185
         _start at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115


Debug message with high or medium severity: `GL_INVALID_OPERATION in glGetProgramStageiv`.
Please report this error: https://github.com/glium/glium/issues
Backtrace:  22 - 0x0
   1 - 0x558195a10341
         _ZN9backtrace9backtrace9libunwind5trace17h8664b0b54fbf4af0E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93
         _ZN9backtrace9backtrace20trace_unsynchronized17hb83f0ff590be0565E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66
   2 - 0x558195a103dc
         _ZN9backtrace9backtrace5trace17hb18e31c5b99d66b2E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53
   3 - 0x558195a13be5
         _ZN5glium7context22default_debug_callback17h61b8e0c89232fee4E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/context/mod.rs:849
   4 - 0x55819586d6fb
         _ZN4core3ops8function5FnMut8call_mut17h2b2454ad74e1bb2bE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:164
   5 - 0x558195a0688c
         _ZN89_$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnMut$LT$Args$GT$$GT$8call_mut17hd92571b0e664990aE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1942
   6 - 0x558195a14dac
         _ZN5glium7context19init_debug_callback16callback_wrapper17h66aad334ae785d9dE at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/context/mod.rs:936
   7 - 0x7f316236b5a1
   8 - 0x5581959c77c9
         _ZN5glium2gl2Gl17GetProgramStageiv17hc2eb3da779289f7bE at /home/moritz/programming/rust/ants/target/debug/build/glium-fae8c5bb5065afdf/out/gl_bindings.rs:6969
   9 - 0x5581959bf5af
         _ZN5glium7program10reflection23reflect_subroutine_data17h27960e08dcd232dcE at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/program/reflection.rs:1240
  10 - 0x55819590e739
         _ZN5glium7program3raw10RawProgram12from_shaders17hb4c8aa288ec48c5fE at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/program/raw.rs:173
  11 - 0x5581958d948c
         _ZN5glium7program7compute13ComputeShader11from_source17h0da2e9316004f507E at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.32.1/src/program/compute.rs:52
  12 - 0x558195878f30
         _ZN4ants4main17h872b8896e5a8cdfbE at /home/moritz/programming/rust/ants/src/main.rs:45
  13 - 0x55819586e9ab
         _ZN4core3ops8function6FnOnce9call_once17h21f73aa820a1d6a8E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248
  14 - 0x5581958c592e
         _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h90d6d3722f992330E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:122
  15 - 0x5581958949d1
         _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17hc2271bb8123a1baeE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:145
  16 - 0x55819600ef0e
         _ZN4core3ops8function5impls72_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$9call_once17hcdfee62722e5e4b8E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280
         _ZN3std9panicking3try7do_call17h84ca51609826746fE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492
         _ZN3std9panicking3try17hd58075e533b8e0cbE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456
         _ZN3std5panic12catch_unwind17h1ebac24d83cb6ce2E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137
         _ZN3std2rt19lang_start_internal28_$u7b$$u7b$closure$u7d$$u7d$17h0145388a1edd1640E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128
         _ZN3std9panicking3try7do_call17h7630182e534a0a32E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492
         _ZN3std9panicking3try17h05b6544f0c6331dcE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456
         _ZN3std5panic12catch_unwind17h77b2ba8fd3309f34E at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137
         _ZN3std2rt19lang_start_internal17h6612c8a7a6861b8bE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128
  17 - 0x5581958949a0
         _ZN3std2rt10lang_start17hc1cb435e3823b32bE at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:144
  18 - 0x55819587996c
         main at <unknown>:??
  19 - 0x7f3164835290
  20 - 0x7f316483534a
         __libc_start_main at <unknown>:??
  21 - 0x558195853185
         _start at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
```
The program won't do what I want, but I don't know yet, if that's due to this issue, or misuse on my part, but because the program asked so nicely, I thought, I would just create this issue :)

Here is the code, where the error occures:
```
fn main() -> Result<(), Error> {
    // Setup window
    let event_loop = EventLoop::new();
    let window_builder = WindowBuilder::new();
    let context_builder = ContextBuilder::new();
    let display = Display::new(window_builder, context_builder, &event_loop)?;

    if !ComputeShader::is_supported(&display) {
        println!("Sorry buddy, no compute for you :(");
        return Ok(());
    }

    let compute_shader = include_str!("shaders/compute.comp");
    let compute_shader = ComputeShader::from_source(&display, compute_shader)?; // <-- Line, where the error occures

    let texture = Texture2d::empty_with_format(
        &display,
        UncompressedFloatFormat::F32F32F32F32,
        MipmapsOption::NoMipmap,
        TEX_WIDTH,
        TEX_HEIGTH,
    )?;

    compute_shader.execute(uniform! { texture: &texture }, TEX_WIDTH, TEX_HEIGTH, 1);

    Ok(())
}
```

Here is some info to my platform as provided by glinfo:
GL_VERSION: 4.6 (Compatibility Profile) Mesa 22.1.7
GL_RENDERER: AMD Radeon RX 5700 (navi10, LLVM 14.0.6, DRM 3.42, 5.15.71-1-MANJARO)
GL_VENDOR: AMD
GL_EXTENSIONS: --- omitted, because A LOT ---
GL_SHADING_LANGUAGE_VERSION = 4.60
GLU_VERSION: 1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
GLUT_API_VERSION: 4
GLUT_XLIB_IMPLEMENTATION: 13

If there are any more questions, just ask :)

**Comment by est31** [comment] 2022-10-08 15:03
Thanks for reaching out. Seems like a dupe of #1718?

**Comment by moritzvoelker** [comment] 2022-10-08 20:31
Yeah, seem's quite like it. So what was the solution? Just ignore it?

**Comment by est31** [comment] 2022-10-08 21:13
Yeah I guess one can just ignore it, and maybe change glium to not make those calls in compute shaders.

**Comment by est31** [comment] 2022-10-08 21:13
Closing this as dupe

**Closed by est31** 2022-10-08 21:13 UTC
