### ISSUE TITLE
docs.rs/glium is gone

### ISSUE THREAD

**Issue by Speykious** [glium/glium#2063] opened 2023-07-03 18:31 UTC
![image](https://github.com/glium/glium/assets/13885008/074442b2-691d-4d1a-b6ff-3dd82c9dd720)

**Comment by jumbledFox** [comment] 2023-07-03 18:33
Godspeed, Glium...
godspeed
o7

**Comment by Astralchroma** [comment] 2023-07-03 18:34
*can confirm, it is gone.*

**Comment by Nemo157** [comment] 2023-07-03 20:19
This was due to a docs.rs bug which accidentally deleted the whole crate from the database, the docs for the latest version are back now and older versions should be queued and rebuilt over the next few days.

**Comment by jumbledFox** [comment] 2023-07-03 21:03
Wow, how'd that even happen? Glad it's back

**Comment by est31** [comment] 2023-07-03 22:18
I've [contacted the crates.io team on zulip](https://rust-lang.zulipchat.com/#narrow/stream/356853-t-docs-rs) and the latest release is available now again on docs.rs. I'm therefore closing this issue as resolved. I want to thank the docs.rs team for the fast help.

> how'd that even happen?

@jumbledFox apparently glium 0.0.1, which was published in the very early days of rust, would now have been impossible to get published. In a cleanup process, they removed that particular crate version, and this was communicated to docs.rs, but somewhere in translation the info was lost that this was just about a single version, so docs.rs removed *all* versions of glium, obviously not what was intended.

**Closed by est31** 2023-07-03 22:18 UTC

**Comment by est31** [comment] 2023-07-04 09:11
Also, btw, thanks @Speykious for reporting this issue, this brought the breakage to my awareness very quickly so that I could ask the right people about it :+1:
