### ISSUE TITLE
Glium tests fail on Windows 10

### ISSUE THREAD

**Issue by Cthutu** [glium/glium#1931] opened 2021-05-30 10:50 UTC
Just by running `cargo test`, I get this failure:
```
Running tests\atomic_counter.rs (target\debug\deps\atomic_counter-19fb0accce3818bf.exe)

running 1 test
test basic ... FAILED

failures:

---- basic stdout ----
thread 'basic' panicked at 'Initializing the event loop outside of the main thread is a significant cross-platform compatibility hazard. If you really, absolutely need to create an EventLoop on a different thread, please use the `EventLoopExtWindows::new_any_thread` function.', C:\Users\matti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:136:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am running Windows 10 on a laptop that supports OpenGL very well.

**Comment by est31** [comment] 2021-05-30 15:36
Thanks for filing, but it's a known bug. Glium would need to get a custom test runner or something. See also #1780 . I'm closing this as duplicate of that bug as the actual segfaults are gone and have been replaced by the message you describe.

**Closed by est31** 2021-05-30 15:36 UTC
